[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
